// Code generated by erygo
package messages

import erygo "github.com/andrepinto/erygo"

// UserCreatedWithSuccess response
func UserCreatedWithSuccess(params ...func(*erygo.Response)) *erygo.Response {
	resp := &erygo.Response{
		Details: []string{},
		Info: erygo.Info{
			Kind:    3,
			Service: "users",
		},
		Message:    "user created with success",
		StatusHTTP: 200,
		Success:    checkStatus(200),
	}
	for _, param := range params {
		param(resp)
	}
	for i, detail := range resp.Details {
		det := renderTemplate(detail)
		resp.Details[i] = det
	}
	return resp
}
